#!/usr/bin/env python3
"""Builds the placeholder low-poly ship and wreck models as OBJ files.

Hulls are lofted from cross-sections, sails are fanned panels with brass
ribs, fittings are prisms and boxes. Faces are flat-shaded on purpose (a
faceted retro look). Each material is its own OBJ group (`usemtl`), which
Godot imports as a separate surface; the scenes set the real materials
with surface overrides.

Output: assets/_ai_generated/models/*__AI.obj, all listed in
assets/ASSET_LEDGER.csv. Models face -Z (Godot's forward), Y up, metres.

    python3 tools/make_models.py
"""

import math
import os

OUT = os.path.join(os.path.dirname(__file__), "..", "assets", "_ai_generated", "models")


# --- Vector helpers -------------------------------------------------------------

def sub(a, b):
    return (a[0] - b[0], a[1] - b[1], a[2] - b[2])


def add(a, b):
    return (a[0] + b[0], a[1] + b[1], a[2] + b[2])


def mul(a, s):
    return (a[0] * s, a[1] * s, a[2] * s)


def cross(a, b):
    return (a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0])


def dot(a, b):
    return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]


def norm(a):
    length = math.sqrt(dot(a, a))
    return (0.0, 1.0, 0.0) if length < 1e-9 else mul(a, 1.0 / length)


def rot_y(p, ang):
    c, s = math.cos(ang), math.sin(ang)
    return (p[0] * c + p[2] * s, p[1], -p[0] * s + p[2] * c)


def rot_z(p, ang):
    c, s = math.cos(ang), math.sin(ang)
    return (p[0] * c - p[1] * s, p[0] * s + p[1] * c, p[2])


def rot_x(p, ang):
    c, s = math.cos(ang), math.sin(ang)
    return (p[0], p[1] * c - p[2] * s, p[1] * s + p[2] * c)


# --- Model -------------------------------------------------------------------------

class Model:
    """Triangles grouped by material name."""

    def __init__(self):
        self.groups = {}

    def tri(self, group, a, b, c, outward=None):
        """Adds a triangle. `outward` is a point the face should point away
        from (a part's centre) or a direction tuple prefixed with 'dir'."""
        n = cross(sub(b, a), sub(c, a))
        if dot(n, n) < 1e-14:
            return
        if outward is not None:
            if outward[0] == "dir":
                want = outward[1]
            else:
                centroid = mul(add(add(a, b), c), 1.0 / 3.0)
                want = sub(centroid, outward)
            if dot(n, want) < 0:
                b, c = c, b
        self.groups.setdefault(group, []).append((a, b, c))

    def quad(self, group, a, b, c, d, outward=None):
        self.tri(group, a, b, c, outward)
        self.tri(group, a, c, d, outward)

    def merge(self, other, transform=lambda p: p):
        for g, tris in other.groups.items():
            for t in tris:
                self.groups.setdefault(g, []).append(tuple(transform(p) for p in t))

    def write(self, name):
        os.makedirs(OUT, exist_ok=True)
        path = os.path.join(OUT, name + "__AI.obj")
        lines = ["# %s: generated by tools/make_models.py (placeholder)" % name]
        v_index = 1
        n_index = 1
        for group in sorted(self.groups):
            lines.append("o %s" % group)
            lines.append("usemtl %s" % group)
            lines.append("s off")
            for a, b, c in self.groups[group]:
                n = norm(cross(sub(b, a), sub(c, a)))
                for p in (a, b, c):
                    lines.append("v %.4f %.4f %.4f" % p)
                lines.append("vn %.4f %.4f %.4f" % n)
                lines.append("f %d//%d %d//%d %d//%d" % (v_index, n_index, v_index + 1, n_index, v_index + 2, n_index))
                v_index += 3
                n_index += 1
        with open(path, "w") as f:
            f.write("\n".join(lines) + "\n")
        count = sum(len(t) for t in self.groups.values())
        print("wrote", os.path.relpath(path), "(%d triangles)" % count)


# --- Parts -------------------------------------------------------------------------

def loft(m, rings, group, top_group=None, cap_group=None):
    """Joins rings of equal length (each a closed loop) into a skin. The
    segment from the last point back to the first is the 'top' (a deck)
    and can use its own material."""
    centre = mul(
        (sum(p[0] for r in rings for p in r), sum(p[1] for r in rings for p in r), sum(p[2] for r in rings for p in r)),
        1.0 / sum(len(r) for r in rings))
    k = len(rings[0])
    for i in range(len(rings) - 1):
        r0, r1 = rings[i], rings[i + 1]
        mid = mul(add(ring_centre(r0), ring_centre(r1)), 0.5)
        for j in range(k):
            j2 = (j + 1) % k
            g = top_group if (top_group and j == k - 1) else group
            if j == k - 1 and top_group:
                m.quad(g, r0[j], r1[j], r1[j2], r0[j2], ("dir", (0, 1, 0)))
            else:
                m.quad(g, r0[j], r1[j], r1[j2], r0[j2], mid)
    for ring, sign in ((rings[0], -1), (rings[-1], 1)):
        c = ring_centre(ring)
        for j in range(k):
            m.tri(cap_group or group, c, ring[j], ring[(j + 1) % k], add(c, (0, 0, -sign * 10)))
    return centre


def ring_centre(r):
    return mul((sum(p[0] for p in r), sum(p[1] for p in r), sum(p[2] for p in r)), 1.0 / len(r))


def prism(m, group, a, b, radius, sides=6, radius_b=None):
    """A capped prism (or tapered cone) from point a to point b."""
    axis = norm(sub(b, a))
    helper = (0, 1, 0) if abs(axis[1]) < 0.9 else (1, 0, 0)
    u = norm(cross(axis, helper))
    v = cross(axis, u)
    rb = radius if radius_b is None else radius_b
    ra_pts, rb_pts = [], []
    for i in range(sides):
        ang = math.tau * i / sides
        off = add(mul(u, math.cos(ang)), mul(v, math.sin(ang)))
        ra_pts.append(add(a, mul(off, radius)))
        rb_pts.append(add(b, mul(off, rb)))
    mid = mul(add(a, b), 0.5)
    for i in range(sides):
        i2 = (i + 1) % sides
        m.quad(group, ra_pts[i], rb_pts[i], rb_pts[i2], ra_pts[i2], mid)
        m.tri(group, a, ra_pts[i], ra_pts[i2], add(a, mul(axis, 10)))
        if rb > 0:
            m.tri(group, b, rb_pts[i], rb_pts[i2], sub(b, mul(axis, 10)))


def box(m, group, centre, size, transform=lambda p: p):
    hx, hy, hz = size[0] / 2, size[1] / 2, size[2] / 2
    corners = [(x, y, z) for x in (-hx, hx) for y in (-hy, hy) for z in (-hz, hz)]
    pts = [transform(add(centre, c)) for c in corners]
    c = transform(centre)
    faces = [(0, 1, 3, 2), (4, 5, 7, 6), (0, 1, 5, 4), (2, 3, 7, 6), (0, 2, 6, 4), (1, 3, 7, 5)]
    for f in faces:
        m.quad(group, pts[f[0]], pts[f[1]], pts[f[2]], pts[f[3]], c)


def fan_sail(m, origin, side, span, angles, lift, sail_group, rib_group, rib=0.035, segments=3):
    """A Treasure Planet style solar sail: panels fanned out sideways from
    `origin`, curving up toward the tips, with brass ribs on the spokes."""
    spokes = []
    for ang in angles:
        pts = []
        for s in range(segments + 1):
            t = s / segments
            d = span * t
            p = (origin[0] + side * d * math.cos(math.radians(ang)), origin[1] + lift * t * t,
                 origin[2] + d * math.sin(math.radians(ang)))
            pts.append(p)
        spokes.append(pts)
    for i in range(len(spokes) - 1):
        a, b = spokes[i], spokes[i + 1]
        for s in range(segments):
            m.quad(sail_group, a[s], b[s], b[s + 1], a[s + 1], ("dir", (0, 1, 0)))
    for pts in spokes:
        for s in range(segments):
            prism(m, rib_group, pts[s], pts[s + 1], rib, 4)


def hull_rings(length, beam, depth, stations=10, sides=7, bow_sheer=0.3, stern_sheer=0.35, deck=0.25,
               stern_width=0.7, start=0.0, end=1.0, jag=None):
    """Cross-sections of a galleon-ish hull, bow at -Z. Each ring runs from
    the left gunwale down round the keel to the right gunwale."""
    rings = []
    for i in range(stations):
        t = start + (end - start) * i / (stations - 1)
        z = -length / 2 + length * t
        w = beam / 2 * max(0.03, min(1.0, (t * 2.2) ** 0.7)) * (1.0 - (1 - stern_width) * max(0.0, t - 0.6) / 0.4)
        d = depth * max(0.08, min(1.0, (t * 2.5) ** 0.5)) * (1.0 - 0.35 * max(0.0, t - 0.75) / 0.25)
        h = deck + bow_sheer * (1 - t) ** 3 + stern_sheer * t ** 4
        ring = []
        for k in range(sides):
            a = -math.pi / 2 + math.pi * k / (sides - 1)
            x = w * math.sin(a)
            y = h - (h + d) * abs(math.cos(a)) ** 0.75
            zz = z
            if jag is not None and i == stations - 1:
                zz += jag[k % len(jag)]
            ring.append((x, y, zz))
        rings.append(ring)
    return rings


# --- Ships -------------------------------------------------------------------------

def sloop():
    m = Model()
    loft(m, hull_rings(4.0, 1.9, 0.6), "wood", top_group="deck", cap_group="wood")
    # Gunwale trim: thin brass rails along both rims.
    rings = hull_rings(4.0, 1.9, 0.6)
    for side in (0, -1):
        for i in range(len(rings) - 1):
            prism(m, "brass", add(rings[i][side], (0, 0.03, 0)), add(rings[i + 1][side], (0, 0.03, 0)), 0.04, 4)
    # Stern castle and its brass lanterns.
    box(m, "wood", (0, 0.55, 1.35), (0.95, 0.4, 0.75))
    box(m, "brass", (0, 0.78, 1.35), (1.05, 0.06, 0.85))
    for x in (-0.45, 0.45):
        prism(m, "glow", (x, 0.8, 1.75), (x, 1.05, 1.75), 0.07, 6)
    # Mast, yard and a small mainsail.
    prism(m, "wood", (0, 0.3, -0.25), (0, 2.1, -0.25), 0.07, 6, 0.05)
    prism(m, "brass", (-0.7, 1.75, -0.25), (0.7, 1.75, -0.25), 0.035, 4)
    main = [(-0.62, 1.72, -0.22), (0.62, 1.72, -0.22), (0.5, 0.75, -0.05), (-0.5, 0.75, -0.05)]
    m.quad("sail", main[0], main[1], main[2], main[3], ("dir", (0, 0, 1)))
    # Bowsprit with a little brass figurehead spike.
    prism(m, "wood", (0, 0.45, -1.8), (0, 0.75, -2.7), 0.06, 5, 0.025)
    prism(m, "brass", (0, 0.42, -1.75), (0, 0.4, -2.15), 0.09, 4, 0.0)
    # Solar sails either side.
    for side in (-1, 1):
        fan_sail(m, (side * 0.75, 0.42, 0.15), side, 1.85, (-38, -15, 8, 30), 0.35, "sail", "brass")
    # Engine nacelle at the stern.
    prism(m, "brass", (0, 0.1, 1.45), (0, 0.1, 2.0), 0.3, 8, 0.24)
    prism(m, "dark", (0, 0.1, 2.0), (0, 0.1, 2.06), 0.22, 8)
    return m


def cutter():
    m = Model()
    loft(m, hull_rings(4.6, 1.5, 0.55, bow_sheer=0.15, stern_sheer=0.2, deck=0.2, stern_width=0.85),
         "hull", top_group="deck", cap_group="hull")
    # A long iron ram.
    prism(m, "iron", (0, 0.2, -2.1), (0, 0.15, -3.1), 0.16, 4, 0.0)
    # Swept-back blade sails, like fins.
    for side in (-1, 1):
        root_f = (side * 0.6, 0.3, -0.6)
        root_b = (side * 0.65, 0.3, 1.1)
        tip = (side * 2.3, 0.6, 1.4)
        m.tri("sail", root_f, root_b, tip, ("dir", (0, 1, 0)))
        prism(m, "iron", root_f, tip, 0.04, 4)
        prism(m, "iron", root_b, tip, 0.04, 4)
    # Spiked dorsal fin.
    fin = [(0, 0.25, -0.8), (0, 0.25, 1.2), (0, 1.4, 1.0)]
    m.tri("sail", fin[0], fin[1], fin[2], ("dir", (1, 0, 0)))
    # Twin engines.
    for x in (-0.35, 0.35):
        prism(m, "iron", (x, 0.15, 1.6), (x, 0.15, 2.4), 0.22, 6, 0.18)
    box(m, "iron", (0, 0.45, 0.5), (0.7, 0.35, 0.9))
    return m


def drone():
    m = Model()
    # Squat faceted body: an octahedron-ish gem, flattened.
    r = 0.75
    top, bottom = (0, 0.55, 0), (0, -0.45, 0)
    ring = [rot_y((r, 0, 0), math.tau * i / 6) for i in range(6)]
    for i in range(6):
        a, b = ring[i], ring[(i + 1) % 6]
        m.tri("metal", top, a, b, (0, 0, 0))
        m.tri("metal", bottom, a, b, (0, 0, 0))
    # Armour band.
    for i in range(6):
        a, b = ring[i], ring[(i + 1) % 6]
        m.quad("dark", add(a, (0, -0.08, 0)), add(b, (0, -0.08, 0)), add(mul(b, 1.12), (0, 0.04, 0)), add(mul(a, 1.12), (0, 0.04, 0)), (0, 0, 0))
    # Three grabbing claws reaching forward.
    for ang in (-0.6, 0.0, 0.6):
        base = rot_y((0, -0.05, -0.6), ang)
        elbow = rot_y((0, -0.15, -1.05), ang * 1.3)
        tip = rot_y((0, -0.05, -1.3), ang * 0.7)
        prism(m, "dark", base, elbow, 0.07, 4)
        prism(m, "dark", elbow, tip, 0.06, 4, 0.0)
    # Side fins.
    for side in (-1, 1):
        a, b, c = (side * 0.7, 0.05, -0.2), (side * 0.7, 0.05, 0.35), (side * 1.25, 0.15, 0.45)
        m.tri("dark", a, b, c, ("dir", (0, 1, 0)))
    return m


def wreck():
    m = Model()
    jag = [0.0, 0.35, -0.2, 0.45, -0.1, 0.3, 0.1]
    loft(m, hull_rings(15.0, 5.0, 1.8, stations=8, deck=0.5, end=0.62, jag=jag), "wood", top_group="deck", cap_group="dark")
    # Snapped mast lying across the deck.
    prism(m, "wood", (0.2, 0.7, -2.6), (3.0, 1.8, 1.4), 0.2, 6, 0.14)
    # Ribs sticking out of the broken end.
    for x in (-1.6, -0.6, 0.6, 1.6):
        prism(m, "dark", (x, -0.5, 1.6), (x * 1.1, 1.0, 2.9), 0.12, 4, 0.06)
    # A torn sail panel draped over the side.
    fan_sail(m, (1.9, 0.7, -3.5), 1, 3.2, (-20, 5, 25), -1.2, "sail", "dark", segments=2)
    return m


def main():
    sloop().write("sloop")
    cutter().write("cutter")
    drone().write("drone")
    wreck().write("wreck")


if __name__ == "__main__":
    main()
